%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=warehouse_user
%prod.quarkus.datasource.password=warehouse_pwd
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/warehouse_db
%prod.quarkus.datasource.jdbc.max-size=8
%prod.quarkus.datasource.jdbc.min-size=2
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.openapi.generator.spec=warehouse-openapi.yaml
quarkus.openapi.generator.base-package=com.warehouse.api
quarkus.datasource.devservices.enabled=false